### ISSUE TITLE
Lab2: Peer Review by Gabriele Greco s303435

### ISSUE THREAD

**Issue by GabriG23** [EnricoMagliano/computational-intelligence#3]
Hello Enrico, I'm Gabriele and this is my peer review for your lab2
## About your solution
- Your solution is similar to mine, I started from one max solution of professor too, but changed it a little bit
- mutation rate of `0.5` is good, I used `0.55`, you could try new values. With higher values it tend to step away from optimal solution with higher values of N, so a lower value is the best choice
- the for loop to check if you found the solution can be expensive for large population and with large num of generations. You can evaluate the new gen after crossover or mutation after the if loop and search for the best solution afterwards
- about the fitness function, the number of set cover minus the number of duplicates it's a good idea. Another one can be to compute the number of distinct elements and the number of total elements of your genome
## About the code and readme
- You can add more info about your code and solution in the readme like for example your results with different kind of iterations, different value of offspring, mutation rate etc...
- Good use of comments, I advice to add more
- You can use a better output format to print solutions in order to compare them and make them readable. For example `INFO:root: Solution for N=10: w=10 (bloat=0%) Fitness calls=1512`, you can add in the main a `for` that loop for different value of N and print different solution. Here's an example:
`for N in [5, 10, 20, 50, 100, 500, 1000]:`
`GA_function(N)`
`logging.info(f" Solution for N={N:,}: " + f"w={w} " + f"(bloat={(w-N)/N*100:.0f}%) " + f"Fitness calls={len(fitness_log)}")`
## Overall
- Good job, keep working like this and improving :)

**Comment by EnricoMagliano** [comment]
Thanks for the review, very exhaustive and complete.
