### ISSUE TITLE
lab3 review - s295483

### ISSUE THREAD

**Issue by dfm88** [EnricoMagliano/computational-intelligence#7]
## Assignment

In general I can say that the approach to the lab was good in terms of ideas. I noticed that you never set the upper bound `k` to the number of removable stick, this makes easier for the optimal strategy to win since can almost always play the best move, while in presence of an upper bound you can limit its choices.

- **pt2**

I used a very similar strategy, using a list of probability as genome, as a rule to choice the most probable strategy between a set of hardcoded strategies, of course this could have also being made parametrizing the parameters of these strategies but it was just another way to do it.

- **pt4**

I can't strictly suggest you how to improve your RL Agent since I had also really poor results. I can tell you what I did differently:

  -- First of all I noticed that you made different behavior  on the training based on the actual turn of the players, I simply made the agent play against itself without evaluating which move to do based on turn but simply giving more reward to the move that a NimSum agent would have done.

-- I also noticed that it seems that you evaluated the whole set of moves as +1 or -1 based on the final match result, I preferred to evaluate very single move at runtime always based on what a NimSum agent would have done (+1 if my agent did the same move of NimSum, +0.3 if my agent did any move, but also the NimSum wouldn't have been able to do an optimal move -you can have this case more often if set a `k` boundary- and -1 if my agent would have the opportunity to do a NimSum move but didn't
 
## Code

I suggest to parametrize more the function and evaluate to use a class from some function with lots of variables. 
The README was quite explicative, but remember also to put some more comments on the key logic

**Comment by EnricoMagliano** [comment]
thanks, for the review, very useful
